name: Mirror Repo
on:
  schedule:
    # Backup nightly
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git clone --mirror 'https://git.sr.ht/~samwhited/mux' mux.git
        cd mux.git/
        git push --mirror "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
